import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const LUA_DIR = join(ROOT, "src", "lua");
const OUT_FILE = join(ROOT, "src", "lua.gen.ts");

// kept a plain comment because luals flags unknown ---@ tags
const DIRECTIVE = /^--\s*needs:\s*(.+?)\s*$/;

export function parseNeeds(source: string): string[] {
  const needs: string[] = [];
  for (const line of source.split("\n")) {
    const m = DIRECTIVE.exec(line);
    if (m) needs.push(...m[1]!.split(/\s+/));
  }
  return needs;
}

export function keyFor(filename: string): string {
  return basename(filename, ".lua").toUpperCase();
}

export function composeChunk(name: string, snippet: string, preludes: Map<string, string>): string {
  const ordered: string[] = [];
  const done = new Set<string>();
  const visiting = new Set<string>();
  const visit = (need: string, neededBy: string): void => {
    if (done.has(need)) return;
    if (visiting.has(need)) throw new Error(`prelude cycle involving "${need}"`);
    const source = preludes.get(need);
    if (source === undefined) throw new Error(`unknown prelude "${need}" needed by ${neededBy}`);
    visiting.add(need);
    for (const dep of parseNeeds(source)) visit(dep, `prelude/${need}.lua`);
    visiting.delete(need);
    done.add(need);
    ordered.push(source);
  };
  for (const need of parseNeeds(snippet)) visit(need, `${name}.lua`);
  const hasCode = snippet.split("\n").some((l) => l.trim() !== "" && !l.trim().startsWith("--"));
  if (!hasCode) throw new Error(`${name}.lua contains no Lua statements`);
  return [...ordered, snippet].join("\n");
}

export function emitModule(chunks: Map<string, string>): string {
  const keys = [...chunks.keys()].sort();
  const body = keys.map((k) => `  ${k}: ${JSON.stringify(chunks.get(k))},`).join("\n");
  return [
    "// GENERATED by scripts/gen-lua.ts. Do not edit; edit src/lua/*.lua and run pnpm gen:lua.",
    "",
    "export const LUA = {",
    body,
    "} as const;",
    "",
  ].join("\n");
}

export function generate(luaDir: string = LUA_DIR): string {
  const preludes = new Map<string, string>();
  const preludeDir = join(luaDir, "prelude");
  if (existsSync(preludeDir)) {
    for (const f of readdirSync(preludeDir)) {
      if (f.endsWith(".lua"))
        preludes.set(basename(f, ".lua"), readFileSync(join(preludeDir, f), "utf8"));
    }
  }
  const chunks = new Map<string, string>();
  for (const f of readdirSync(luaDir)) {
    if (!f.endsWith(".lua")) continue;
    const snippet = readFileSync(join(luaDir, f), "utf8");
    chunks.set(keyFor(f), composeChunk(basename(f, ".lua"), snippet, preludes));
  }
  if (chunks.size === 0) throw new Error(`no .lua snippets found in ${luaDir}`);
  return emitModule(chunks);
}

function main(): void {
  const content = generate();
  if (process.argv.includes("--verify")) {
    const current = existsSync(OUT_FILE) ? readFileSync(OUT_FILE, "utf8") : null;
    if (current !== content) {
      console.error("src/lua.gen.ts is stale; run pnpm gen:lua");
      process.exit(1);
    }
    return;
  }
  writeFileSync(OUT_FILE, content);
  console.log(`wrote ${OUT_FILE}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
